Fixed VisIt reader build script for older versions.
Also removed a few compiler warnings and added a fallback
to build the serial version of the reader if all else fails.

diff --git a/VisIt/SDF/build b/VisIt/SDF/build
--- a/VisIt/SDF/build
+++ b/VisIt/SDF/build
@@ -6,20 +6,23 @@ version=`visit -version 2>&1 | sed 's,.* \([0-9]*\).*,\1,'`
 tmpdir=.tmp
 
 clean=0
+build_visit_reader=1
+build_utilities=0
 DBG=""
 DEBUG=""
 PRIVATE="-private"
 VERBOSE=""
-OPTS="$*"
+OPTS=""
 
-while getopts cdpv name
+while getopts cdpnuv name
 do
-   echo $name $OPTIND $OPTARG
    case $name in
-      c) clean=1 ;;
-      d) DBG="-g -O0";
+      c) clean=1 ; OPTS="$OPTS -c";;
+      d) DBG="-g -O0"; OPTS="$OPTS -d";
          DEBUG="-DCMAKE_BUILD_TYPE=Debug" ;;
       p) PRIVATE="-public" ;;
+      n) build_visit_reader=0 ;;
+      u) build_utilities=1 ;;
       v) VERBOSE="VERBOSE=1" ;;
    esac
 done
@@ -60,10 +63,20 @@ PY_CXXFLAGS=-I$(TOPDIR)/include/python,;s,\(^LDFLAGS.*\),\1 -m32 $DBG," Makefile
       fi
     else
       xml2cmake -clobber $PRIVATE ${fmt}${version}.xml
-      for f in `grep -w INCLUDE CMakeLists.txt | cut -f2 -d\"`; do
+      for f in `grep -w INCLUDE CMakeLists.txt | cut -f2 -d\( | \
+          cut -f1 -d\) | tr -d \"`; do
         base=`basename $f`
-        sed 's,/usr/lib/libmpi[^;]*.dylib,,g;s,/usr/lib/libopen[^;]*.dylib,,g' $f > $tmpdir/$base
-        sed 's,INCLUDE("'$f',INCLUDE("'$tmpdir/$base',' \
+        sed 's,/[^;]*libmpi[^;]*;,,g;s,/[^;]*libopen-[^;]*;,,g' \
+            $f > $tmpdir/$base
+        if [ $build_parallel -eq 1 ]; then
+          grep -v 'CMAKE_CXX_COMPILER ' $tmpdir/$base | \
+              grep -v 'CMAKE_C_COMPILER ' > $tmpdir/tmp
+          mv $tmpdir/tmp $tmpdir/$base
+        elif [ $build_serial -eq 1 ]; then
+          grep -v 'VISIT_PARALLEL ' $tmpdir/$base > $tmpdir/tmp
+          mv $tmpdir/tmp $tmpdir/$base
+        fi
+        sed 's,\(INCLUDE(["]*\)'$f'\(["]*\),\1'$tmpdir/$base'\2,' \
             CMakeLists.txt > $tmpdir/tmp
         mv $tmpdir/tmp CMakeLists.txt
       done
@@ -71,7 +84,7 @@ PY_CXXFLAGS=-I$(TOPDIR)/include/python,;s,\(^LDFLAGS.*\),\1 -m32 $DBG," Makefile
     fi
 
     make clean
-    make 2> $tmpdir/err
+    make $VERBOSE
   else
     echo "Unable to build. Please add visit to your \$PATH"
   fi
@@ -80,29 +93,49 @@ PY_CXXFLAGS=-I$(TOPDIR)/include/python,;s,\(^LDFLAGS.*\),\1 -m32 $DBG," Makefile
 
 if [ $clean -eq 1 ]; then
   make clean > /dev/null 2>&1
-  rm -rf CMake* cmake* Makefile SDF*Info.C SDF*Info.h
-else
+  rm -rf CMake* cmake* Makefile ${fmt}*Info.C ${fmt}*Info.h
+elif [ $build_visit_reader -eq 1 ]; then
+  srl=""
+  err=0
+  build_parallel=0
+  build_serial=0
   buildit
   
   if [ $? -ne 0 ]; then
-    mpi=0
-    grep -w mpi.h $tmpdir/err > /dev/null && mpi=1
-    grep -w lmpi $tmpdir/err > /dev/null && mpi=1
-    grep -w MPI $tmpdir/err > /dev/null && mpi=1
-    grep libmpi $tmpdir/err > /dev/null && mpi=1
-    if [ $mpi -ne 0 ]; then
-      echo "Trying again with mpicc"
-      # Execute in a subshell to stop CC being altered in the current shell.
-      (export CC=mpicc
-      export CXX=mpicxx
-      buildit)
-    else
-      cat $tmpdir/err
-    fi
+    build_parallel=1
+    echo
+    echo "Trying again with mpicc"
+    # Execute in a subshell to stop CC being altered in the current shell.
+    (export CC=mpicc
+    export CXX=mpicxx
+    buildit)
+    [ $? -ne 0 ] && err=1
+    build_parallel=0
   fi
+
+  if [ $err -ne 0 ]; then
+    err=0
+    build_serial=1
+    echo
+    echo "Trying again without parallel reader."
+    srl=" (Serial version only)."
+    buildit
+    [ $? -ne 0 ] && err=1
+    build_serial=0
+  fi
+
+  if [ $err -ne 0 ]; then
+    echo "ERROR: Failed to build VisIt reader."
+    exit 1
+  fi
+
+  echo
+  echo "VisIt ${fmt} reader successfully built.${srl}"
 fi
 
 [ -x ./extension/build ] && ./extension/build $OPTS
-[ -x ./utilities/build ] && ./utilities/build $OPTS
+if [ $build_utilities -eq 1 ]; then
+  [ -x ./utilities/build ] && ./utilities/build $OPTS
+fi
 
 rm -rf $tmpdir
